const properties = [
  {
    lat: 37.53296477,
    lon: 126.9810179,
    link: "https://www.dragonhilllodge.com/",
    name: "Dragon Hill Lodge",
    proptype: "af resort",
  },
  {
    lat: 47.4820402,
    lon: 11.06444594,
    link: "https://www.edelweisslodgeandresort.com/",
    name: "Eedelweiss Lodge and Resort",
    proptype: "af resort",
  },
  {
    lat: 28.40206719,
    lon: -81.59158894,
    link: "https://www.shadesofgreen.org/",
    name: "Shades Of Green",
    proptype: "af resort",
  },
  {
    lat: 21.28171302,
    lon: -157.8347532,
    link: "https://www.halekoa.com/",
    name: "Hale Koa",
    proptype: "af resort",
  },
  {
    lat: 31.326356,
    lon: -85.719685,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-rucker/mfkra/hoteldetail",
    name: "Holiday Inn Express Building 308",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 31.326981,
    lon: -85.717368,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-rucker/mfkrb/hoteldetail",
    name: "IHG Army Hotels Building 100-300 Series",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 34.679285,
    lon: -86.629347,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/redstone-arsenal/zyrea/hoteldetail",
    name: "Candlewood Suites Building 3440",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 64.822939,
    lon: -147.631464,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-wainright/mfwak/hoteldetail",
    name: "Holiday Inn Express Northern Lights Inn",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 31.553836,
    lon: -110.353081,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-huachuca/mfhuc/hoteldetail",
    name: "Candlewood Suites Building 44420",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 31.549144,
    lon: -110.36034,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-huachuca/mfhua/hoteldetail",
    name: "IHG Army Hotels Main Complex Buildings",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 32.862222,
    lon: -114.437778,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/yuma-proving-ground/mfyub/hoteldetail",
    name: "Candlewood Suites Building 540",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 32.861077,
    lon: -114.437075,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/yuma-proving-ground/mfyua/hoteldetail",
    name: "IHG Army Hotels La Casita",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 36.011346,
    lon: -121.243583,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/jolon/zyica/hoteldetail",
    name: "IHG Army Hotels Gibb Hall",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 37.720583,
    lon: -121.903304,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/dublin/zycpa/hoteldetail",
    name: "IHG Army Hotels Buildings 1150 &amp; 1151",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 36.606009,
    lon: -121.907202,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/presidio-of-monterey/zypra/hoteldetail",
    name: "IHG Army Hotels Buildings 366 &amp; 367",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 38.7362294,
    lon: -104.8026268,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-carson/zysoa/hoteldetail",
    name: "Candlewood Suites Building 7306",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 32.358877,
    lon: -84.958949,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-benning/zybea/hoteldetail",
    name: "Holiday Inn Express Abrams Hall",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 32.361969,
    lon: -84.962511,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-benning/zybeb/hoteldetail",
    name: "IHG Army Hotels Gavin House",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 33.41,
    lon: -82.133333,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-gordon/mfgrd/hoteldetail",
    name: "Candlewood Suites Building 38300",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 33.426267,
    lon: -82.122277,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-gordon/mfgra/hoteldetail",
    name: "Holiday Inn Express Griffith Hall",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 31.874665,
    lon: -81.607872,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-stewart/zyfwa/hoteldetail",
    name: "IHG Army Hotels Main Lodge",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 32.027176,
    lon: -81.124694,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/savannah/zyhga/hoteldetail",
    name: "Holiday Inn Express Building 6007",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 32.02754,
    lon: -81.122072,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/hunter-army-airfield/zyhgb/hoteldetail",
    name: "IHG Army Hotels DVQs Buildings 6012 &amp; 6013",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 21.361406,
    lon: -157.886879,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/tripler-amc/mftrb/hoteldetail",
    name: "IHG Army Hotels Building 228",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 21.348188,
    lon: -157.884246,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-shaforter/mftra/hoteldetail",
    name: "IHG Army Hotels Building 719",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 39.342385,
    lon: -94.922164,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-leavenworth/mfvwa/hoteldetail",
    name: "Holiday Inn Express Hoge Hall",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 39.35556,
    lon: -94.920556,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-leavenworth/mfvwb/hoteldetail",
    name: "IHG Army Hotels Otis &amp; Custer House - Historia",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 39.098611,
    lon: -96.816667,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-riley/mflyd/hoteldetail",
    name: "Candlewood Suites Building 6956",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 39.064177,
    lon: -96.781681,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-riley/mflyb/hoteldetail",
    name: "IHG Army Hotels Bacon &amp; Waters Hall - Historia",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 36.642778,
    lon: -87.445,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-campbell/mfcaa/hoteldetail",
    name: "Holiday Inn Express Turner Guesthouse",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 37.898923,
    lon: -85.955839,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-knox/mfkxa/hoteldetail",
    name: "Holiday Inn Express Newgarden Inn",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 37.880316,
    lon: -85.941291,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-knox/mfkxb/hoteldetail",
    name: "Holiday Inn Express Wickam Inn",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 37.917686,
    lon: -85.943466,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-knox/mfkxd/hoteldetail",
    name: "IHG Army Hotels Craig &amp; Knierim Apartments",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 37.893408,
    lon: -85.95314,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-knox/mfkxc/hoteldetail",
    name: "IHG Army Hotels Yeomans Hall - Historia",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 31.049444,
    lon: -93.219167,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-polk/mfpkb/hoteldetail",
    name: "Holiday Inn Express Magnolia House &amp; Cypress Inn",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 39.4844968,
    lon: -76.1289246,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/aberdeen-proving-ground/zyapb/hoteldetail",
    name: "Candlewood Suites Building 2250",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 39.101377,
    lon: -76.743582,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-meade/zyeab/hoteldetail",
    name: "Candlewood Suites Building 4690",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 37.761731,
    lon: -92.1104,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-leonard-wood/mflwe/hoteldetail",
    name: "Candlewood Suites Building 2020",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 37.773878,
    lon: -92.109661,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-leonard-wood/mflwb/hoteldetail",
    name: "Holiday Inn Express Morelli Heights",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 37.763691,
    lon: -92.108806,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-leonard-wood/mflwa/hoteldetail",
    name: "IHG Army Hotels Foster Lodge",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 37.777797,
    lon: -92.116174,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-leonard-wood/mflwc/hoteldetail",
    name: "IHG Army Hotels Warrior Lodge",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 32.380686,
    lon: -106.487272,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/white-sands-missile-range/mfwsa/hoteldetail",
    name: "IHG Army Hotels Buildings 501, 502, 506",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 44.038158,
    lon: -75.800829,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-drum/zyumb/hoteldetail",
    name: "Candlewood Suites Building 9090",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 40.611908,
    lon: -74.028379,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/brooklyn/mfham/hoteldetail",
    name: "Holiday Inn Express Building 107",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 41.394354,
    lon: -73.962225,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/west-point/zywpb/hoteldetail",
    name: "IHG Army Hotels Beat Navy House - Historia",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 41.371667,
    lon: -73.961944,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/west-point/zywpa/hoteldetail",
    name: "IHG Army Hotels Five Star Inn",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 35.128611,
    lon: -78.996667,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-bragg/zygga/hoteldetail",
    name: "IHG Army Hotels Moon Hall",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 35.145421,
    lon: -78.990498,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-bragg/zyggd/hoteldetail",
    name: "IHG Army Hotels Normandy House &amp; Carolina Inn",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 34.661667,
    lon: -98.396111,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-sill/mfokb/hoteldetail",
    name: "Holiday Inn Express Allin/Aultman Hall",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 34.662258,
    lon: -98.397455,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-sill/mfoka/hoteldetail",
    name: "IHG Army Hotels 5600 Series",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 34.672248,
    lon: -98.387539,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-sill/mfoke/hoteldetail",
    name: "IHG Army Hotels Comanche House - Historia",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 40.206468,
    lon: -77.178758,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/carlisle/zyjia/hoteldetail",
    name: "IHG Army Hotels Carlisle Barracks - Historia",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 34.0193619,
    lon: -80.927527,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/columbia/zykje/hoteldetail",
    name: "Candlewood Suites East Building 10050",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 34.0193619,
    lon: -80.927527,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/columbia/zykjd/hoteldetail",
    name: "Candlewood Suites West Building 10046",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 34.018678,
    lon: -80.92775,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/columbia/zykja/hoteldetail",
    name: "Holiday Inn Express Fort Jackson Inn",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 34.021328,
    lon: -80.926683,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/columbia/zykjb/hoteldetail",
    name: "IHG Army Hotels Dozier Hall",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 31.829743,
    lon: -106.393377,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-bliss/mfbld/hoteldetail",
    name: "Candlewood Suites Building 11193",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 31.82401,
    lon: -106.42844,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-bliss/mfbla/hoteldetail",
    name: "Holiday Inn Express Guesthouse",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 31.137222,
    lon: -97.760556,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-hood/mfhdd/hoteldetail",
    name: "Candlewood Suites Building 144",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 31.13112,
    lon: -97.771427,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-hood/mfhdc/hoteldetail",
    name: "Holiday Inn Express Keith Ware Hall",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 29.453474,
    lon: -98.447413,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-sam-houston/mfshd/hoteldetail",
    name: "Candlewood Suites Building 2426",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 29.4625,
    lon: -98.451667,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-sam-houston/mfshe/hoteldetail",
    name: "Holiday Inn Express Building 592",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 29.457681,
    lon: -98.420173,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-sam-houston/mfshb/hoteldetail",
    name: "Holiday Inn Express Powless House",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 29.463302,
    lon: -98.436463,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-sam-houston/mfsha/hoteldetail",
    name: "IHG Army Hotels Building 1384",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 29.445278,
    lon: -98.466389,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-sam-houston/mfshc/hoteldetail",
    name: "IHG Army Hotels Foulois House - Historia",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 40.224928,
    lon: -112.742246,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/dugway/zydpa/hoteldetail",
    name: "Holiday Inn Express Desert Lodge",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 38.693,
    lon: -77.1309,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-belvoir/mfbva/hoteldetail",
    name: "Holiday Inn Express Knadle Hall",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 38.708159,
    lon: -77.140748,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-belvoir/mfbvc/hoteldetail",
    name: "Staybridge Suites Building 1208",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 37.226997,
    lon: -77.345238,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-lee/zylea/hoteldetail",
    name: "Holiday Inn Express Building 12015",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 37.233459,
    lon: -77.339928,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-lee/zyleb/hoteldetail",
    name: "IHG Army Hotels MacKintosh Buildings",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 38.885556,
    lon: -77.080278,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-myer/mfmyb/hoteldetail",
    name: "IHG Army Hotels Wainwright Hall - Historia",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 47.1226284,
    lon: -122.4914555,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/joint-base-lewis-mcchord/zylmc/hoteldetail",
    name: "Candlewood Suites Building J0550",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 47.0907,
    lon: -122.600802,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/joint-base-lewis-mcchord/zylma/hoteldetail",
    name: "Holiday Inn Express Rainier Inn &amp; Rainier Complex",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 47.089722,
    lon: -122.615,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/joint-base-lwis-mcchord/zylmb/hoteldetail",
    name: "IHG Army Hotels Bronson Hall - Historia",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 47.129722,
    lon: -122.485833,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/joint-base-lewis-mcchord/zylmd/hoteldetail",
    name: "IHG Army Hotels Buildings 600 Series",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 44.011163,
    lon: -90.67066,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-mccoy/zyyma/hoteldetail",
    name: "IHG Army Hotels Anderson Hall",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 18.41726,
    lon: -66.123536,
    link: "https://www.ihg.com/armyhotels/hotels/us/en/fort-buchanan/mfbua/hoteldetail",
    name: "Holiday Inn Express El Caney Lodge",
    proptype: "IHG Army Hotels",
  },
  {
    lat: 57.7564,
    lon: -152.5003774,
    link: "http://www.kodiakmwr.com/guest_house.shtml",
    name: "Kodiak Nemetz RV Park",
    proptype: "coast guard rec",
  },
  {
    lat: 57.7564,
    lon: -152.5003774,
    link: "http://www.kodiakmwr.com/guest_house.shtml",
    name: "Kodiak Guest House",
    proptype: "coast guard vacation rental",
  },
  {
    lat: 34.1618,
    lon: -119.2209596,
    link: "https://www.coastguardmwr.org/_files/ugd/458cd4_250d5fc8170c4eeeafb0ccfbeb212280.pdf",
    name: "Channel Islands Harbor RV Park",
    proptype: "coast guard rec",
  },
  {
    lat: 39.18272737,
    lon: -120.1190639,
    link: "https://reservations.vacationrentaldesk.com/StationLakeTahoe/homepage.html",
    name: "Lake Tahoe Recreational Lodging",
    proptype: "coast guard vacation rental",
  },
  {
    lat: 38.0516,
    lon: -122.5147504,
    link: "https://www.dcms.uscg.mil/Our-Organization/Director-of-Operational-Logistics-DOL/Bases/Base-Alameda/Alameda-Personnel-Support-Department/Alameda-Morale-Well-Being-and-Recreation/Alameda-Novato-Temporary-Quarters/",
    name: "Novato Temporary Quarters (TQ) Rentals",
    proptype: "coast guard vacation rental",
  },
  {
    lat: 38.248395,
    lon: -122.7820531,
    link: "https://www.petalumamwr.com/guest-lodging/",
    name: "Petaluma Guest House",
    proptype: "coast guard vacation rental",
  },
  {
    lat: 38.248395,
    lon: -122.7820531,
    link: "https://www.petalumamwr.com/campground/",
    name: "Petaluma Lake RV Park",
    proptype: "coast guard rec",
  },
  {
    lat: 41.3837,
    lon: -72.10561269,
    link: "https://www.cgamwr.com/guest-housing/",
    name: "Munro Hall Guest Quarters",
    proptype: "coast guard vacation rental",
  },
  {
    lat: 26.2597,
    lon: -80.08099315,
    link: "https://www.coastguardmwr.org/_files/ugd/458cd4_5f9e16c1947b4d3da7a3bb643e28fb7d.pdf",
    name: "Hillsboro Recreational Cottages",
    proptype: "coast guard vacation rental",
  },
  {
    lat: 24.7101,
    lon: -81.10656344,
    link: "https://www.dcms.uscg.mil/Our-Organization/Director-of-Operational-Logistics-DOL/Bases/Base-Miami-Beach/MWR/MWR-Marathon/",
    name: "Marathon Recreation Cottages",
    proptype: "coast guard rec",
  },
  {
    lat: 24.7101,
    lon: -81.10656344,
    link: "https://www.dcms.uscg.mil/Our-Organization/Director-of-Operational-Logistics-DOL/Bases/Base-Miami-Beach/MWR/MWR-Marathon/",
    name: "Marathon Recreation RV Pads",
    proptype: "coast guard vacation rental",
  },
  {
    lat: 39.2015,
    lon: -76.57103014,
    link: "https://www.dcms.uscg.mil/Our-Organization/Assistant-Commandant-for-Engineering-Logistics-CG-4-/Logistic-Centers/Surface-Forces-Logistics-Center/Coast-Guard-Yard/YARD-MWR/Guest-Housing/",
    name: "Coast Guard Yard Family Lodging",
    proptype: "coast guard vacation rental",
  },
  {
    lat: 41.6595,
    lon: -70.56949267,
    link: "https://mwrcapecod.com/facilities/mwr-lodging/base-cape-cod-recreation-house/",
    name: "Base Cape Cod Recreation House",
    proptype: "coast guard vacation rental",
  },
  {
    lat: 41.6595,
    lon: -70.56949803,
    link: "https://mwrcapecod.com/facilities/mwr-lodging/wings-inn/",
    name: "Wings Inn",
    proptype: "coast guard vacation rental",
  },
  {
    lat: 41.6592,
    lon: -70.569393,
    link: "https://mwrcapecod.com/facilities/mwr-lodging/mwr-townhouses/",
    name: "Lemay Townhouses",
    proptype: "coast guard vacation rental",
  },
  {
    lat: 41.651,
    lon: -70.5799917,
    link: "https://mwrcapecod.com/facilities/mwr-lodging/rv-park/",
    name: "Cape Cod RV Park",
    proptype: "coast guard rec",
  },
  {
    lat: 42.3676,
    lon: -71.05298329,
    link: "https://www.dcms.uscg.mil/Portals/10/DOL/BaseBoston/CuttyHunk_Application_2021.pdf?ver=dBYuR5P-IZC7eGvCoSDpXg%3D%3D",
    name: "Cuttyhunk Island Recreational Lodging",
    proptype: "coast guard vacation rental",
  },
  {
    lat: 43.0595,
    lon: -86.24025577,
    link: "http://reservations.vacationrentaldesk.com/pika9qdlqr1.html",
    name: "Point Betsie Recreation Cottage",
    proptype: "coast guard vacation rental",
  },
  {
    lat: 39.1287,
    lon: -74.709536,
    link: "https://www.atlanticarea.uscg.mil/Our-Organization/District-5/District-Units/Air-Station-Atlantic-City/MWR/Townsend-Inlet-Recreational-Facility/",
    name: "Townsend Inlet Recreational Lodging",
    proptype: "coast guard vacation rental",
  },
  {
    lat: 38.9475,
    lon: -74.89078318,
    link: "https://www.forcecom.uscg.mil/Our-Organization/FORCECOM-UNITS/TraCen-Cape-May/Visitor-Services/Guest-Quarters/",
    name: "Cape May Temporary Housing",
    proptype: "coast guard rec",
  },
  {
    lat: 38.9477,
    lon: -74.88384101,
    link: "https://www.forcecom.uscg.mil/Our-Organization/FORCECOM-UNITS/TraCen-Cape-May/Recreation-Morale/Camping/",
    name: "Cape May Camping",
    proptype: "coast guard rec",
  },
  {
    lat: 40.6041,
    lon: -74.06303426,
    link: "https://www.coastguardmwr.org/_files/ugd/458cd4_12c7d2d2e487413eaf229a071642345c.pdf",
    name: "Fort Wadsworth Guest Quarters",
    proptype: "coast guard vacation rental",
  },
  {
    lat: 40.5989,
    lon: -74.06212436,
    link: "https://www.coastguardmwr.org/_files/ugd/458cd4_12c7d2d2e487413eaf229a071642345c.pdf",
    name: "Navy Lodge New York",
    proptype: "coast guard rec",
  },
  {
    lat: 36.2702,
    lon: -76.17977327,
    link: "https://www.coastguardmwr.org/_files/ugd/458cd4_dbeb5ffa6f0a4fd69f64a642605cc857.pdf",
    name: "Elizabeth City Lodging RV Park",
    proptype: "coast guard rec",
  },
  {
    lat: 36.2703,
    lon: -76.1797742,
    link: "https://www.coastguardmwr.org/_files/ugd/458cd4_dbeb5ffa6f0a4fd69f64a642605cc857.pdf",
    name: "Elizabeth City Lodging",
    proptype: "coast guard vacation rental",
  },
  {
    lat: 18.497,
    lon: -67.13153313,
    link: "https://vrentals.vacationrentaldesk.com/AguadillaGuestHouses/homepage.html",
    name: "Air Station Borinquen Cottages",
    proptype: "coast guard vacation rental",
  },
  {
    lat: 18.3991,
    lon: -66.1560326,
    link: "https://vrentals.vacationrentaldesk.com/BaseSanJuanCGMWRLodging/homepage.html",
    name: "Rio Bayamon Guest Housing",
    proptype: "coast guard vacation rental",
  },
  {
    lat: 37.2176,
    lon: -76.47673797,
    link: "https://www.forcecom.uscg.mil/Our-Organization/FORCECOM-UNITS/TraCen-Yorktown/Reporting/Guest-Quarters/",
    name: "Cain Hall Guest Quarters",
    proptype: "coast guard vacation rental",
  },
  {
    lat: 46.88901,
    lon: -124.11717,
    link: "https://www.coastguardmwr.org/_files/ugd/458cd4_eabec1aa2fd24fc2b7f438c25e40bba1.pdf",
    name: "Westport Lighthouse Campground and RV Park",
    proptype: "coast guard rec",
  },
  {
    lat: 43.7495,
    lon: -87.70359171,
    link: "http://rentals.vacationrentaldesk.com/a8928ce436ea45aaa3188214fb194332/homepage.html",
    name: "Rawley Point Cottage",
    proptype: "coast guard vacation rental",
  },
  {
    lat: 44.7946,
    lon: -87.31329005,
    link: "http://rentals.vacationrentaldesk.com/a8928ce436ea45aaa3188214fb194332/homepage.html",
    name: "Sherwood Point Cottage",
    proptype: "coast guard vacation rental",
  },
  {
    lat: 30.182027,
    lon: -85.753398,
    link: "https://get.dodlodging.net/propertys/Panama-City-Navy-Getaway-RV-Park--Cabins",
    name: "Panama City Navy Getaway RV Park , Cabins",
    proptype: "Navy VacationRental",
  },
  {
    lat: 30.182027,
    lon: -85.753398,
    link: "https://get.dodlodging.net/propertys/Panama-City-Navy-Getaway-RV-Park--Cabins",
    name: "Panama City Navy Getaway RV Park , Cabins",
    proptype: "Navy RV",
  },
  {
    lat: 32.792905,
    lon: -117.102188,
    link: "https://get.dodlodging.net/propertys/Admiral-Baker-Park",
    name: "Admiral Baker Park",
    proptype: "Navy RV",
  },
  {
    lat: 32.8193121,
    lon: -115.6962142,
    link: "https://get.dodlodging.net/propertys/El-Centro-RV-Park",
    name: "El Centro RV Park",
    proptype: "Navy RV",
  },
  {
    lat: 36.261943,
    lon: -119.898572,
    link: "https://get.dodlodging.net/propertys/Navy-Getaways-Lemoore-RV-Park",
    name: "Navy Getaways Lemoore RV Park",
    proptype: "Navy RV",
  },
  {
    lat: 36.590636,
    lon: -121.861339,
    link: "https://get.dodlodging.net/propertys/Monterey-RV-Park-",
    name: "Monterey RV Park",
    proptype: "Navy RV",
  },
  {
    lat: 32.651201,
    lon: -117.149765,
    link: "https://get.dodlodging.net/propertys/Fiddlers-Cove-Marina--RV-Park",
    name: "Fiddlers Cove Marina , RV Park",
    proptype: "Navy RV",
  },
  {
    lat: 34.1725606,
    lon: -119.2067649,
    link: "https://get.dodlodging.net/propertys/Fairways-RV-Resort-NB-Ventura-County-Port-Hueneme",
    name: "Fairways RV Resort NB Ventura County Port Hueneme",
    proptype: "Navy RV",
  },
  {
    lat: 38.9827,
    lon: -76.487778,
    link: "https://get.dodlodging.net/propertys/Annapolis",
    name: "Navy Getaways Annapolis",
    proptype: "Navy VacationRental",
  },
  {
    lat: 38.9827,
    lon: -76.487778,
    link: "https://get.dodlodging.net/propertys/Annapolis",
    name: "Navy Getaways Annapolis",
    proptype: "Navy RV",
  },
  {
    lat: 37.29583722,
    lon: -76.62989616,
    link: "https://get.dodlodging.net/propertys/Cheatham-Annex-Outdoors-and-Cottages",
    name: "Cheatham Annex Outdoors and Cottages",
    proptype: "Navy VacationRental",
  },
  {
    lat: 37.29583722,
    lon: -76.62989616,
    link: "https://get.dodlodging.net/propertys/Cheatham-Annex-Outdoors-and-Cottages",
    name: "Cheatham Annex Outdoors and Cottages",
    proptype: "Navy RV",
  },
  {
    lat: 48.3375,
    lon: -122.68725,
    link: "https://get.dodlodging.net/propertys/Cliffside-RV-Park",
    name: "Cliffside RV Park",
    proptype: "Navy VacationRental",
  },
  {
    lat: 48.3375,
    lon: -122.68725,
    link: "https://get.dodlodging.net/propertys/Cliffside-RV-Park",
    name: "Cliffside RV Park",
    proptype: "Navy RV",
  },
  {
    lat: 42.308823,
    lon: -87.834114,
    link: "https://get.dodlodging.net/propertys/Great-Lakes-RV-Campground",
    name: "Great Lakes RV Campground",
    proptype: "Navy RV",
  },
  {
    lat: 48.224747,
    lon: -121.946522,
    link: "https://get.dodlodging.net/propertys/Jim-Creek-Recreation-Area",
    name: "Jim Creek Recreation Area",
    proptype: "Navy VacationRental",
  },
  {
    lat: 48.224747,
    lon: -121.946522,
    link: "https://get.dodlodging.net/propertys/Jim-Creek-Recreation-Area",
    name: "Jim Creek Recreation Area",
    proptype: "Navy RV",
  },
  {
    lat: 34.089519,
    lon: -84.720851,
    link: "https://get.dodlodging.net/propertys/Navy-Lake-Site-Allatoona",
    name: "Navy Lake Site Allatoona",
    proptype: "Navy VacationRental",
  },
  {
    lat: 34.089519,
    lon: -84.720851,
    link: "https://get.dodlodging.net/propertys/Navy-Lake-Site-Allatoona",
    name: "Navy Lake Site Allatoona",
    proptype: "Navy RV",
  },
  {
    lat: 36.795302,
    lon: -76.024485,
    link: "https://get.dodlodging.net/propertys/Ocean-Pines-RV-Park",
    name: "Ocean Pines RV Park",
    proptype: "Navy RV",
  },
  {
    lat: 47.216314,
    lon: -124.203745,
    link: "https://get.dodlodging.net/propertys/Navy-Getaways-Pacific-Beach",
    name: "Navy Getaways Pacific Beach",
    proptype: "Navy VacationRental",
  },
  {
    lat: 47.216314,
    lon: -124.203745,
    link: "https://get.dodlodging.net/propertys/Navy-Getaways-Pacific-Beach",
    name: "Navy Getaways Pacific Beach",
    proptype: "Navy RV",
  },
  {
    lat: 26.3021715,
    lon: 127.9111962,
    link: "https://get.dodlodging.net/propertys/Okinawa-Navy-Getaways",
    name: "Okinawa Navy Getaways",
    proptype: "Navy VacationRental",
  },
  {
    lat: 26.3021715,
    lon: 127.9111962,
    link: "https://get.dodlodging.net/propertys/Okinawa-Navy-Getaways",
    name: "Okinawa Navy Getaways",
    proptype: "Navy RV",
  },
  {
    lat: 38.344,
    lon: -76.4675,
    link: "https://get.dodlodging.net/propertys/Navy-Getaways-Solomons",
    name: "Navy Getaways Solomons",
    proptype: "Navy VacationRental",
  },
  {
    lat: 38.344,
    lon: -76.4675,
    link: "https://get.dodlodging.net/propertys/Navy-Getaways-Solomons",
    name: "Navy Getaways Solomons",
    proptype: "Navy RV",
  },
  {
    lat: 44.95367,
    lon: -68.282425,
    link: "https://get.dodlodging.net/propertys/Great-Pond-Outdoor-Adventure-Center",
    name: "Great Pond Outdoor Adventure Center",
    proptype: "Navy VacationRental",
  },
  {
    lat: 44.95367,
    lon: -68.282425,
    link: "https://get.dodlodging.net/propertys/Great-Pond-Outdoor-Adventure-Center",
    name: "Great Pond Outdoor Adventure Center",
    proptype: "Navy RV",
  },
  {
    lat: 40.85161,
    lon: 14.11017,
    link: "https://get.dodlodging.net/propertys/Carney-Park-Lodging-Naples",
    name: "Carney Park Lodging Naples",
    proptype: "Navy VacationRental",
  },
  {
    lat: 40.85161,
    lon: 14.11017,
    link: "https://get.dodlodging.net/propertys/Carney-Park-Lodging-Naples",
    name: "Carney Park Lodging Naples",
    proptype: "Navy RV",
  },
  {
    lat: 21.303693,
    lon: -158.046176,
    link: "https://get.dodlodging.net/propertys/Barbers-Point-Beach-Cottages",
    name: "Barbers Point Beach Cottages",
    proptype: "Navy VacationRental",
  },
  {
    lat: 27.500362,
    lon: -97.820289,
    link: "https://get.dodlodging.net/propertys/Rocking-K-RV-Park",
    name: "Rocking K RV Park",
    proptype: "Navy RV",
  },
  {
    lat: 38.833333,
    lon: -86.791667,
    link: "https://get.dodlodging.net/propertys/Lake-Greenwood",
    name: "Lake Greenwood",
    proptype: "Navy VacationRental",
  },
  {
    lat: 38.833333,
    lon: -86.791667,
    link: "https://get.dodlodging.net/propertys/Lake-Greenwood",
    name: "Lake Greenwood",
    proptype: "Navy RV",
  },
  {
    lat: 35.49801536,
    lon: 139.3949349,
    link: "https://army.dodlodging.net/propertys/Camp-Zama-Lodging",
    name: "Camp Zama Lodging",
    proptype: "Army Hotel",
  },
  {
    lat: 34.74256464,
    lon: -120.5363274,
    link: "https://af.dodlodging.net/propertys/Vandenberg-AFB",
    name: "Vandenberg AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 32.61272,
    lon: -83.586473,
    link: "https://af.dodlodging.net/propertys/Robins-AFB",
    name: "Robins AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 28.24572309,
    lon: -80.60256958,
    link: "https://af.dodlodging.net/propertys/Patrick-AFB",
    name: "Patrick AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 33.89193494,
    lon: -117.2739029,
    link: "https://af.dodlodging.net/propertys/March-AFB",
    name: "March AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 27.85070667,
    lon: -82.48155355,
    link: "https://af.dodlodging.net/propertys/MacDill-AFB",
    name: "MacDill AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 29.355661,
    lon: -100.783841,
    link: "https://af.dodlodging.net/propertys/Laughlin-AFB",
    name: "Laughlin AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 30.41192912,
    lon: -88.92370462,
    link: "https://af.dodlodging.net/propertys/Keesler-AFB",
    name: "Keesler AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 30.42321669,
    lon: -86.63475037,
    link: "https://af.dodlodging.net/propertys/Hurlburt-Field",
    name: "Hurlburt Field",
    proptype: "Air Force Hotel",
  },
  {
    lat: 25.49802987,
    lon: -80.39614677,
    link: "https://af.dodlodging.net/propertys/Homestead-ARB",
    name: "Homestead ARB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 30.48460926,
    lon: -86.50220633,
    link: "https://af.dodlodging.net/propertys/Eglin-AFB",
    name: "Eglin AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 30.65222,
    lon: -86.529617,
    link: "https://af.dodlodging.net/propertys/Duke-Field",
    name: "Duke Field",
    proptype: "Air Force Hotel",
  },
  {
    lat: 39.115708,
    lon: -121.3887,
    link: "https://af.dodlodging.net/propertys/Beale-AFB",
    name: "Beale AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 35.32745068,
    lon: -86.06964111,
    link: "https://af.dodlodging.net/propertys/Arnold-AFB",
    name: "Arnold AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 36.6340301,
    lon: -6.3490369,
    link: "https://ngis.dodlodging.net/propertys/Rota-NS",
    name: "Naval Station Rota",
    proptype: "Navy Hotel",
  },
  {
    lat: 35.15555,
    lon: 128.6555,
    link: "https://ngis.dodlodging.net/propertys/Chinhae-CFA-",
    name: "Commander Fleet Activities Chinhae",
    proptype: "Navy Hotel",
  },
  {
    lat: 35.284167,
    lon: 139.668023,
    link: "https://ngis.dodlodging.net/propertys/Yokosuka-CFA-",
    name: "Commander Fleet Activities Yokosuka",
    proptype: "Navy Hotel",
  },
  {
    lat: 40.87914305,
    lon: 14.28903267,
    link: "https://ngis.dodlodging.net/propertys/Naples-NSA-",
    name: "Naval Support Activity Naples",
    proptype: "Navy Hotel",
  },
  {
    lat: 35.4546924,
    lon: 139.4350219,
    link: "https://ngis.dodlodging.net/propertys/Atsugi-NAF-",
    name: "Naval Air Facility Atsugi",
    proptype: "Navy Hotel",
  },
  {
    lat: 48.33853682,
    lon: -122.6786613,
    link: "https://ngis.dodlodging.net/propertys/Whidbey-Island-NAS-",
    name: "Naval Air Station Whidbey Island",
    proptype: "Navy Hotel",
  },
  {
    lat: 26.3516955,
    lon: 127.7694715,
    link: "https://ngis.dodlodging.net/propertys/Okinawa-CFA-",
    name: "Commander Fleet Activities Okinawa",
    proptype: "Navy Hotel",
  },
  {
    lat: 13.36228301,
    lon: 144.6873826,
    link: "https://ngis.dodlodging.net/propertys/Joint-Region-Marianas-NB-Guam",
    name: "Joint Region Marianas Naval Base Guam",
    proptype: "Navy Hotel",
  },
  {
    lat: 36.566934,
    lon: -76.248422,
    link: "https://ngis.dodlodging.net/propertys/Northwest-Annex-NSA-",
    name: "Naval Support Activity Northwest Annex",
    proptype: "Navy Hotel",
  },
  {
    lat: 36.920075,
    lon: -76.308509,
    link: "https://ngis.dodlodging.net/propertys/Hampton-Roads-Norfolk-NSA-",
    name: "Naval Support Activity Hampton Roads Norfolk ",
    proptype: "Navy Hotel",
  },
  {
    lat: 32.768132,
    lon: -97.418774,
    link: "https://ngis.dodlodging.net/propertys/NAS-JRB-FORT-WORTH",
    name: "Naval Air Station Joint Reserve Base Fort Worth",
    proptype: "Navy Hotel",
  },
  {
    lat: -7.3099865,
    lon: 72.4070682,
    link: "https://ngis.dodlodging.net/propertys/Diego-Garcia-NSF",
    name: "Navy Support Facility Diego Garcia",
    proptype: "Navy Hotel",
  },
  {
    lat: 47.68877807,
    lon: -122.7127361,
    link: "https://ngis.dodlodging.net/propertys/Kitsap-Bangor-NB",
    name: "Naval Base Kitsap Bangor ",
    proptype: "Navy Hotel",
  },
  {
    lat: 29.82617,
    lon: -90.016994,
    link: "https://ngis.dodlodging.net/propertys/NAS-JRB-New-Orleans",
    name: "Naval Air Station Joint Reserve Base New Orleans ",
    proptype: "Navy Hotel",
  },
  {
    lat: 47.56358306,
    lon: -122.6460671,
    link: "https://ngis.dodlodging.net/propertys/Kitsap-Bremerton-NB",
    name: "Naval Base Kitsap Bremerton",
    proptype: "Navy Hotel",
  },
  {
    lat: 42.316262,
    lon: -87.832694,
    link: "https://ngis.dodlodging.net/propertys/Naval-Station-Great-Lakes-",
    name: "Naval Station Great Lakes ",
    proptype: "Navy Hotel",
  },
  {
    lat: 30.35219434,
    lon: -87.27736473,
    link: "https://ngis.dodlodging.net/propertys/Pensacola-NAS",
    name: "Naval Air Station Pensacola ",
    proptype: "Navy Hotel",
  },
  {
    lat: 32.725261,
    lon: -117.22065,
    link: "https://ngis.dodlodging.net/propertys/Point-Loma-NB-Annex",
    name: "Naval Base Point Loma, North Harbor Drive Annex",
    proptype: "Navy Hotel",
  },
  {
    lat: 36.807045,
    lon: -76.023183,
    link: "https://ngis.dodlodging.net/propertys/Oceana-NAS-",
    name: "Naval Air Station Oceana",
    proptype: "Navy Hotel",
  },
  {
    lat: 36.59440919,
    lon: -121.874281,
    link: "https://get.dodlodging.net/propertys/Monterey-Hotel-Del-Monte",
    name: "Hotel Del Monte",
    proptype: "Navy Hotel",
  },
  {
    lat: 34.121393,
    lon: -119.099532,
    link: "https://ngis.dodlodging.net/propertys/Point-Mugu-NBVC",
    name: "Naval Base Ventura County Point Mugu",
    proptype: "Navy Hotel",
  },
  {
    lat: 36.908801,
    lon: -76.14075,
    link: "https://ngis.dodlodging.net/propertys/Little-Creek-Ft.Story-JEB-",
    name: "Joint Expeditionary Base Little Creek Fort Story",
    proptype: "Navy Hotel",
  },
  {
    lat: 32.82062272,
    lon: -115.675081,
    link: "https://ngis.dodlodging.net/propertys/El-Centro-NAF",
    name: "Naval Air Facility El Centro",
    proptype: "Navy Hotel",
  },
  {
    lat: 41.51648,
    lon: -71.321834,
    link: "https://ngis.dodlodging.net/propertys/Newport-NS",
    name: "Naval Station Newport",
    proptype: "Navy Hotel",
  },
  {
    lat: 39.41489717,
    lon: -118.7250423,
    link: "https://ngis.dodlodging.net/propertys/Fallon-NAS-",
    name: "Naval Air Station Fallon",
    proptype: "Navy Hotel",
  },
  {
    lat: 38.26987523,
    lon: -76.44922256,
    link: "https://ngis.dodlodging.net/propertys/Patuxent-River-NAS-",
    name: "Naval Air Station Patuxent River",
    proptype: "Navy Hotel",
  },
  {
    lat: 21.349736,
    lon: -157.940529,
    link: "https://ngis.dodlodging.net/propertys/Pearl-Harbor-JB-Hickam(Pearl-Harbor-Side",
    name: "Joint Base Pearl Harbor Hickam (Pearl Harbor Side)",
    proptype: "Navy Hotel",
  },
  {
    lat: 21.340237,
    lon: -157.954789,
    link: "https://ngis.dodlodging.net/propertys/Pearl-Harbor-JB-Hickam(Hickam-Side)",
    name: "Joint Base Pearl Harbor Hickam (Hickam Side, Royal Alaka)",
    proptype: "Navy Hotel",
  },
  {
    lat: 30.391419,
    lon: -81.402745,
    link: "https://get.dodlodging.net/propertys/Mayport-Recreational-Lodging",
    name: "Mayport Recreational Lodging",
    proptype: "Navy VacationRental",
  },
  {
    lat: 30.391419,
    lon: -81.402745,
    link: "https://get.dodlodging.net/propertys/Mayport-Recreational-Lodging",
    name: "Mayport Recreational Lodging",
    proptype: "Navy RV",
  },
  {
    lat: 30.790802,
    lon: -81.565279,
    link: "https://ngis.dodlodging.net/propertys/Kings-Bay-NSB",
    name: "Naval Submarine Base Kings Bay",
    proptype: "Navy Hotel",
  },
  {
    lat: 30.70623988,
    lon: -87.0210287,
    link: "https://ngis.dodlodging.net/propertys/Whiting-Field-NAS",
    name: "Naval Air Station Whiting Field ",
    proptype: "Navy Hotel",
  },
  {
    lat: 35.309924,
    lon: 139.582337,
    link: "https://get.dodlodging.net/propertys/Ikego-West-Valley-Campgrounds",
    name: "Ikego West Valley Campgrounds",
    proptype: "VacationRental",
  },
  {
    lat: 35.309924,
    lon: 139.582337,
    link: "https://get.dodlodging.net/propertys/Ikego-West-Valley-Campgrounds",
    name: "Ikego West Valley Campgrounds",
    proptype: "Navy RV",
  },
  {
    lat: 41.390224,
    lon: -72.080659,
    link: "https://ngis.dodlodging.net/propertys/New-London-NSB",
    name: "Naval Submarine Base New London",
    proptype: "Navy Hotel",
  },
  {
    lat: 32.68453626,
    lon: -117.1191931,
    link: "https://ngis.dodlodging.net/propertys/San-Diego-NB",
    name: "Naval Base San Diego",
    proptype: "Navy Hotel",
  },
  {
    lat: 22.03588345,
    lon: -159.783504,
    link: "https://get.dodlodging.net/propertys/Navy-Getaways-Barking-Sands",
    name: "Navy Getaways Barking Sands",
    proptype: "Navy VacationRental",
  },
  {
    lat: 32.69527,
    lon: -117.198034,
    link: "https://ngis.dodlodging.net/propertys/North-Island-NAS",
    name: "NAS North Island Coronado",
    proptype: "Navy Hotel",
  },
  {
    lat: 27.688649,
    lon: -97.258011,
    link: "https://get.dodlodging.net/propertys/Navy-Getaways-NAS-Corpus-Christi-RV-Park",
    name: "Navy Getaways NAS Corpus Christi RV Park",
    proptype: "Navy RV",
  },
  {
    lat: 33.75053468,
    lon: -118.0891657,
    link: "https://get.dodlodging.net/propertys/Seal-Beach-RV-Park-(Seabreeze)-",
    name: "Seal Beach RV Park (Seabreeze)",
    proptype: "Navy RV",
  },
  {
    lat: 49.71028,
    lon: 11.90314,
    link: "https://army.dodlodging.net/propertys/Grafenwoehr-Lodging",
    name: "Grafenwoehr Lodging",
    proptype: "Army Hotel",
  },
  {
    lat: 49.230434,
    lon: 11.82437897,
    link: "https://army.dodlodging.net/propertys/Hohenfels-Lodging",
    name: "Hohenfels Lodging",
    proptype: "Army Hotel",
  },
  {
    lat: 36.25867019,
    lon: -119.8970175,
    link: "https://ngis.dodlodging.net/propertys/Lemoore-NAS",
    name: "Naval Air Station Lemoore",
    proptype: "Navy Hotel",
  },
  {
    lat: 40.69472041,
    lon: 141.3621461,
    link: "https://ngis.dodlodging.net/propertys/Misawa-NAF-",
    name: "Naval Air Facility Misawa",
    proptype: "Navy Hotel",
  },
  {
    lat: 33.162075,
    lon: 129.718292,
    link: "https://ngis.dodlodging.net/propertys/Sasebo-CFA-",
    name: "Commander Fleet Activities Sasebo ",
    proptype: "Navy Hotel",
  },
  {
    lat: 37.411223,
    lon: 14.909134,
    link: "https://ngis.dodlodging.net/propertys/Sigonella-NAS",
    name: "Naval Air Station Sigonella",
    proptype: "Navy Hotel",
  },
  {
    lat: 35.53119596,
    lon: 24.15150046,
    link: "https://ngis.dodlodging.net/propertys/Souda-Bay-NSA",
    name: "Naval Support Activity Souda Bay",
    proptype: "Navy Hotel",
  },
  {
    lat: 26.207482,
    lon: 50.611133,
    link: "https://ngis.dodlodging.net/propertys/Bahrain-NSA",
    name: "Naval Support Activity Bahrain",
    proptype: "Navy Hotel",
  },
  {
    lat: 37.931552,
    lon: -75.479936,
    link: "https://ngis.dodlodging.net/propertys/Wallops-Island-SCSC",
    name: "Surface Combat Systems Center Wallops Island",
    proptype: "Navy Hotel",
  },
  {
    lat: 36.94758695,
    lon: -76.30454892,
    link: "https://ngis.dodlodging.net/propertys/Norfolk-NS",
    name: "Naval Station Norfolk",
    proptype: "Navy Hotel",
  },
  {
    lat: 38.32862876,
    lon: -77.03789234,
    link: "https://ngis.dodlodging.net/propertys/Dahlgren-NSF-",
    name: "Naval Support Facility Dahlgren",
    proptype: "Navy Hotel",
  },
  {
    lat: 43.080835,
    lon: -70.7310295,
    link: "https://ngis.dodlodging.net/propertys/Portsmouth-NSY",
    name: "Portsmouth Naval Shipyard",
    proptype: "Navy Hotel",
  },
  {
    lat: 30.374306,
    lon: -89.129306,
    link: "https://ngis.dodlodging.net/propertys/Gulfport-NCBC-",
    name: "Naval Construction Battalion Center Gulfport ",
    proptype: "Navy Hotel",
  },
  {
    lat: 38.05434298,
    lon: -78.50574732,
    link: "https://army.dodlodging.net/propertys/The-Judge-Advocate-Generals-Legal-Ctr.--School-Lodging",
    name: "The Judge Advocate Generals Legal Ctr. , School Lodging",
    proptype: "Army Hotel",
  },
  {
    lat: 49.62894869,
    lon: 11.78850174,
    link: "https://army.dodlodging.net/propertys/Vilseck-Lodging-",
    name: "Vilseck Lodging ",
    proptype: "Army Hotel",
  },
  {
    lat: 45.54952854,
    lon: 11.58125134,
    link: "https://army.dodlodging.net/propertys/Vicenza-Lodging",
    name: "Vicenza Lodging",
    proptype: "Army Hotel",
  },
  {
    lat: 50.07615,
    lon: 8.270637,
    link: "https://army.dodlodging.net/propertys/Wiesbaden-Lodge",
    name: "Wiesbaden Lodge",
    proptype: "Army Hotel",
  },
  {
    lat: 30.18081758,
    lon: -85.75395915,
    link: "https://ngis.dodlodging.net/propertys/Panama-City-NSA-",
    name: "Naval Support Activity Panama City ",
    proptype: "Navy Hotel",
  },
  {
    lat: 24.561881,
    lon: -81.792505,
    link: "https://ngis.dodlodging.net/propertys/Key-West-NAS",
    name: "Naval Air Station Key West",
    proptype: "Navy Hotel",
  },
  {
    lat: 30.19948355,
    lon: -81.68583862,
    link: "https://ngis.dodlodging.net/propertys/Jacksonville-NAS",
    name: "Naval Air Station Jacksonville",
    proptype: "Navy Hotel",
  },
  {
    lat: 32.684833,
    lon: -117.235326,
    link: "https://ngis.dodlodging.net/propertys/Point-Loma-NB-Main-Base",
    name: "Naval Base Point Loma, Main Base",
    proptype: "Navy Hotel",
  },
  {
    lat: 32.671645,
    lon: -117.16294,
    link: "https://ngis.dodlodging.net/propertys/Coronado-NAB",
    name: "Naval Amphibious Base Coronado",
    proptype: "Navy Hotel",
  },
  {
    lat: 34.1599806,
    lon: -119.1965398,
    link: "https://ngis.dodlodging.net/propertys/Port-Hueneme-NBVC",
    name: "Naval Base Ventura County Port Hueneme ",
    proptype: "Navy Hotel",
  },
  {
    lat: 35.65338012,
    lon: -117.6525719,
    link: "https://ngis.dodlodging.net/propertys/China-Lake-NAWS-",
    name: "Naval Air Weapons Station China Lake",
    proptype: "Navy Hotel",
  },
  {
    lat: 19.924564,
    lon: -75.138371,
    link: "https://ngis.dodlodging.net/propertys/Guantanamo-Bay-NS",
    name: "Naval Station Guantanamo Bay",
    proptype: "Navy Hotel",
  },
  {
    lat: 1.453546,
    lon: 103.828178,
    link: "https://ngis.dodlodging.net/propertys/SAC-Singapore-Area-Coordinator",
    name: "SAC Singapore Area Coordinator",
    proptype: "Navy Hotel",
  },
  {
    lat: 13.58325578,
    lon: 144.9244308,
    link: "https://ngis.dodlodging.net/propertys/Andersen-NSA-AFB-Guam",
    name: "NSA Andersen Air Force Base, Guam",
    proptype: "Navy Hotel",
  },
  {
    lat: 33.2524698,
    lon: -119.5000076,
    link: "https://ngis.dodlodging.net/propertys/San-Nicolas-Island-NBVC",
    name: "San Nicolas Island NBVC",
    proptype: "Navy Hotel",
  },
  {
    lat: 32.997756,
    lon: -118.555495,
    link: "https://ngis.dodlodging.net/propertys/San-Clemente-Island-NALF",
    name: "San Clemente Island",
    proptype: "Navy Hotel",
  },
  {
    lat: 24.579152,
    lon: -81.776779,
    link: "https://get.dodlodging.net/propertys/Key-West-Campground",
    name: "Key West Campground",
    proptype: "Navy RV",
  },
  {
    lat: 49.31863235,
    lon: 10.64334869,
    link: "https://army.dodlodging.net/propertys/Ansbach-Lodging",
    name: "Ansbach Lodging",
    proptype: "Army Hotel",
  },
  {
    lat: 49.61109925,
    lon: 7.32049942,
    link: "https://army.dodlodging.net/propertys/Baumholder-Lodging",
    name: "Baumholder Lodging",
    proptype: "Army Hotel",
  },
  {
    lat: 37.9176957,
    lon: 127.0562173,
    link: "https://army.dodlodging.net/propertys/Camp-Casey-Lodging",
    name: "Camp Casey Lodging",
    proptype: "Army Hotel",
  },
  {
    lat: 37.82280243,
    lon: 128.7597656,
    link: "https://army.dodlodging.net/propertys/Camp-Humphreys",
    name: "Camp Humphreys",
    proptype: "Army Hotel",
  },
  {
    lat: 36.05576062,
    lon: 128.4109497,
    link: "https://army.dodlodging.net/propertys/Camp-Carroll-Lodging",
    name: "Camp Carroll Lodging",
    proptype: "Army Hotel",
  },
  {
    lat: 35.8379894,
    lon: 128.5870135,
    link: "https://army.dodlodging.net/propertys/Camp-Walker--Camp-Henry-Lodging",
    name: "Camp Walker , Camp Henry Lodging",
    proptype: "Army Hotel",
  },
  {
    lat: 50.588739,
    lon: 3.8171,
    link: "https://army.dodlodging.net/propertys/Chievres-Lodging",
    name: "Chievres Lodging",
    proptype: "Army Hotel",
  },
  {
    lat: 52.37554678,
    lon: -0.218267441,
    link: "https://af.dodlodging.net/propertys/RAF-Alconbury",
    name: "RAF Alconbury",
    proptype: "Air Force Hotel",
  },
  {
    lat: 38.81133923,
    lon: -76.8845129,
    link: "https://af.dodlodging.net/propertys/Joint-Base-Andrews",
    name: "Joint Base Andrews",
    proptype: "Air Force Hotel",
  },
  {
    lat: 33.64720713,
    lon: -88.44423294,
    link: "https://af.dodlodging.net/propertys/Columbus-AFB",
    name: "Columbus AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 39.80640963,
    lon: -84.04165506,
    link: "https://af.dodlodging.net/propertys/Wright-Patterson-AFB",
    name: "Wright Patterson AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 42.201414,
    lon: -72.544397,
    link: "https://af.dodlodging.net/propertys/Westover-ARB",
    name: "Westover ARB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 36.926171,
    lon: -76.012604,
    link: "https://get.dodlodging.net/propertys/Getaways-Fort-Story--67th-Street-Townhouses",
    name: "Getaways Fort Story , 67th Street Townhouses",
    proptype: "Navy VacationRental",
  },
  {
    lat: 36.926171,
    lon: -76.012604,
    link: "https://get.dodlodging.net/propertys/Getaways-Fort-Story--67th-Street-Townhouses",
    name: "Getaways Fort Story , 67th Street Townhouses",
    proptype: "Navy RV",
  },
  {
    lat: 30.07496189,
    lon: -85.60538292,
    link: "https://af.dodlodging.net/propertys/Tyndall-AFB",
    name: "Tyndall AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 38.27390142,
    lon: -121.9462681,
    link: "https://af.dodlodging.net/propertys/Travis-AFB",
    name: "Travis AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 52.00084116,
    lon: -1.20677948,
    link: "https://af.dodlodging.net/propertys/RAF-Croughton",
    name: "RAF Croughton",
    proptype: "Air Force Hotel",
  },
  {
    lat: 44.15018848,
    lon: -103.0737305,
    link: "https://af.dodlodging.net/propertys/Ellsworth-AFB",
    name: "Ellsworth AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 61.24274359,
    lon: -149.8562622,
    link: "https://af.dodlodging.net/propertys/JB-Elmendorf-Richardson",
    name: "JB Elmendorf Richardson",
    proptype: "Air Force Hotel",
  },
  {
    lat: 35.42846982,
    lon: -97.41420507,
    link: "https://af.dodlodging.net/propertys/Tinker-AFB",
    name: "Tinker AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 33.97392779,
    lon: -80.48389792,
    link: "https://af.dodlodging.net/propertys/Shaw-AFB",
    name: "Shaw AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 35.3568562,
    lon: -77.96355486,
    link: "https://af.dodlodging.net/propertys/Seymour-Johnson-AFB",
    name: "Seymour Johnson AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 38.5446405,
    lon: -89.85245,
    link: "https://af.dodlodging.net/propertys/Scott-AFB",
    name: "Scott AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 41.11440876,
    lon: -95.91493607,
    link: "https://af.dodlodging.net/propertys/Offutt-AFB",
    name: "Offutt AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 36.24257721,
    lon: -115.0448799,
    link: "https://af.dodlodging.net/propertys/Nellis-AFB",
    name: "Nellis AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 40.66045704,
    lon: -86.1500001,
    link: "https://af.dodlodging.net/propertys/Grissom-AFB",
    name: "Grissom AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 32.406707,
    lon: -86.244662,
    link: "https://af.dodlodging.net/propertys/Maxwell-AFB",
    name: "Maxwell AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 26.36384701,
    lon: 127.7660146,
    link: "https://af.dodlodging.net/propertys/Kadena-AB",
    name: "Kadena AB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 35.01952359,
    lon: -106.5293598,
    link: "https://af.dodlodging.net/propertys/Kirtland-AFB",
    name: "Kirtland AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 37.6225257,
    lon: -97.25698471,
    link: "https://af.dodlodging.net/propertys/McConnell-AFB",
    name: "McConnell AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 34.89557603,
    lon: -92.14396477,
    link: "https://af.dodlodging.net/propertys/Little-Rock-AFB",
    name: "Little Rock AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 37.09681225,
    lon: -76.35369301,
    link: "https://af.dodlodging.net/propertys/Joint-Base-Langley-Eustis",
    name: "Joint Base Langley Eustis",
    proptype: "Air Force Hotel",
  },
  {
    lat: 40.263713,
    lon: -74.16225,
    link: "https://get.dodlodging.net/propertys/Navy-Getaways-Deer-Run-Lodging",
    name: "Navy Getaways Deer Run Lodging",
    proptype: "Navy VacationRental",
  },
  {
    lat: 32.898611,
    lon: -80.040556,
    link: "https://af.dodlodging.net/propertys/JB---Charleston-AFB",
    name: "JB   Charleston AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 41.15112802,
    lon: -104.8490524,
    link: "https://af.dodlodging.net/propertys/FE-Warren-AFB",
    name: "FE Warren AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 32.19399077,
    lon: -110.8749676,
    link: "https://af.dodlodging.net/propertys/Davis-Monthan-AFB",
    name: "Davis Monthan AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 48.418457,
    lon: -101.321227,
    link: "https://af.dodlodging.net/propertys/Minot-AFB",
    name: "Minot AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 43.10098288,
    lon: -78.94105911,
    link: "https://af.dodlodging.net/propertys/Niagara-Falls-ARB",
    name: "Niagara Falls ARB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 52.393957,
    lon: 0.5488591,
    link: "https://af.dodlodging.net/propertys/RAF-Lakenheath",
    name: "RAF Lakenheath",
    proptype: "Air Force Hotel",
  },
  {
    lat: 39.00868004,
    lon: -104.8891783,
    link: "https://af.dodlodging.net/propertys/AF-Academy",
    name: "AF Academy",
    proptype: "Air Force Hotel",
  },
  {
    lat: 37.157444,
    lon: -5.607662,
    link: "https://af.dodlodging.net/propertys/Moron-AB",
    name: "Moron AB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 49.444467,
    lon: 7.587476,
    link: "https://af.dodlodging.net/propertys/Ramstein-Inns-Ramstein",
    name: "Ramstein Inns Ramstein",
    proptype: "Air Force Hotel",
  },
  {
    lat: 34.39047915,
    lon: -103.3366728,
    link: "https://af.dodlodging.net/propertys/Cannon-AFB",
    name: "Cannon AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 38.737632,
    lon: -93.5759,
    link: "https://af.dodlodging.net/propertys/Whiteman-Inn",
    name: "Whiteman AFB, Missouri",
    proptype: "Air Force Hotel",
  },
  {
    lat: 32.49928397,
    lon: -93.67496967,
    link: "https://af.dodlodging.net/propertys/Barksdale-Inn",
    name: "Barksdale AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 39.125533,
    lon: -75.474615,
    link: "https://af.dodlodging.net/propertys/Dover-AFB",
    name: "Dover AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 47.627508,
    lon: -117.664452,
    link: "https://af.dodlodging.net/propertys/Fairchild-AFB",
    name: "Fairchild AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 34.91572498,
    lon: -117.9352069,
    link: "https://af.dodlodging.net/propertys/Edwards-",
    name: "Edwards ",
    proptype: "Air Force Hotel",
  },
  {
    lat: 31.43269115,
    lon: -100.4098892,
    link: "https://af.dodlodging.net/propertys/Goodfellow-AFB",
    name: "Goodfellow AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 32.8346,
    lon: -106.08736,
    link: "https://af.dodlodging.net/propertys/Holloman-AFB",
    name: "Holloman AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 40.035556,
    lon: -74.351111,
    link: "https://af.dodlodging.net/propertys/JBMDL---Navy-Lakehurst",
    name: "JBMDL   Navy Lakehurst",
    proptype: "Air Force Hotel",
  },
  {
    lat: 47.51847596,
    lon: -111.1841297,
    link: "https://af.dodlodging.net/propertys/Malmstrom-AFB",
    name: "Malmstrom AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 30.979724,
    lon: -83.200428,
    link: "https://af.dodlodging.net/propertys/Moody-AFB",
    name: "Moody AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 38.82537955,
    lon: -104.7001219,
    link: "https://af.dodlodging.net/propertys/Peterson-AFB",
    name: "Peterson AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 36.34330274,
    lon: -97.90779591,
    link: "https://af.dodlodging.net/propertys/Vance-AFB",
    name: "Vance AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 32.42615904,
    lon: -99.83400822,
    link: "https://af.dodlodging.net/propertys/Dyess-AFB",
    name: "Dyess AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 37.15327075,
    lon: -76.575737,
    link: "https://af.dodlodging.net/propertys/Fort-Eustis",
    name: "Fort Eustis",
    proptype: "Air Force Hotel",
  },
  {
    lat: 41.12501291,
    lon: -111.9732571,
    link: "https://af.dodlodging.net/propertys/Hill-AFB-UT",
    name: "Hill AFB, UT",
    proptype: "Air Force Hotel",
  },
  {
    lat: 35.92745498,
    lon: 126.6158585,
    link: "https://af.dodlodging.net/propertys/Kunsan-AB-Korea",
    name: "Kunsan AB, Korea",
    proptype: "Air Force Hotel",
  },
  {
    lat: 38.759292,
    lon: -27.078048,
    link: "https://af.dodlodging.net/propertys/Lajes-Field-Azores",
    name: "Lajes Field, Azores",
    proptype: "Air Force Hotel",
  },
  {
    lat: 44.89646782,
    lon: -93.21474552,
    link: "https://af.dodlodging.net/propertys/Minneapolis-St-Paul-ARS",
    name: "Minneapolis St Paul ARS",
    proptype: "Air Force Hotel",
  },
  {
    lat: 37.52715362,
    lon: 126.9799805,
    link: "https://af.dodlodging.net/propertys/Osan-AB-Korea",
    name: "Osan AB, Korea",
    proptype: "Air Force Hotel",
  },
  {
    lat: 49.405486,
    lon: 7.563091,
    link: "https://af.dodlodging.net/propertys/Landstuhl",
    name: "Landstuhl",
    proptype: "Air Force Hotel",
  },
  {
    lat: 49.974724,
    lon: 6.699167,
    link: "https://af.dodlodging.net/propertys/Spangdahlem-AB",
    name: "Spangdahlem AB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 41.268708,
    lon: -80.677493,
    link: "https://af.dodlodging.net/propertys/Youngstown-ARS",
    name: "Youngstown ARS",
    proptype: "Air Force Hotel",
  },
  {
    lat: 40.036288,
    lon: -74.575884,
    link: "https://af.dodlodging.net/propertys/JBMDL---McGuire-Dix-Lakehurst-",
    name: "JBMDL   McGuire Dix Lakehurst ",
    proptype: "Air Force Hotel",
  },
  {
    lat: 43.05187745,
    lon: -115.8535337,
    link: "https://af.dodlodging.net/propertys/Mountain-Home",
    name: "Mountain Home",
    proptype: "Air Force Hotel",
  },
  {
    lat: 29.525772,
    lon: -98.281988,
    link: "https://af.dodlodging.net/propertys/JBSA---Randolph-",
    name: "JBSA   Randolph ",
    proptype: "Air Force Hotel",
  },
  {
    lat: 34.54604983,
    lon: -99.42208529,
    link: "https://af.dodlodging.net/propertys/Altus-AFB",
    name: "Altus AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 37.283363,
    lon: -76.604588,
    link: "https://ngis.dodlodging.net/propertys/Cheatham-Annex-NWSY",
    name: "NWS Yorktown Cheatham Annex",
    proptype: "Navy Hotel",
  },
  {
    lat: 36.78811014,
    lon: -75.9594284,
    link: "https://ngis.dodlodging.net/propertys/Dam-Neck-Annex-NAS",
    name: "Dam Neck Annex",
    proptype: "Navy Hotel",
  },
  {
    lat: 64.6776749,
    lon: -147.0817852,
    link: "https://af.dodlodging.net/propertys/Eielson-AFB",
    name: "Eielson AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 37.00344375,
    lon: 35.42550087,
    link: "https://af.dodlodging.net/propertys/Incirlik-AB",
    name: "Incirlik AB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 33.540332,
    lon: -112.359775,
    link: "https://af.dodlodging.net/propertys/Luke-AFB",
    name: "Luke AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 40.70491227,
    lon: 141.3674811,
    link: "https://af.dodlodging.net/propertys/Misawa-AB-Japan",
    name: "Misawa AB, Japan",
    proptype: "Air Force Hotel",
  },
  {
    lat: 33.96923877,
    lon: -98.50328922,
    link: "https://af.dodlodging.net/propertys/Sheppard-AFB",
    name: "Sheppard AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 49.438281,
    lon: 7.714393,
    link: "https://af.dodlodging.net/propertys/Vogelweh",
    name: "Vogelweh",
    proptype: "Air Force Hotel",
  },
  {
    lat: 46.0354072,
    lon: 12.60191917,
    link: "https://af.dodlodging.net/propertys/Aviano",
    name: "Aviano",
    proptype: "Air Force Hotel",
  },
  {
    lat: 33.91352013,
    lon: -84.51147079,
    link: "https://af.dodlodging.net/propertys/Dobbins-ARB",
    name: "Dobbins ARB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 36.809085,
    lon: -76.314611,
    link: "https://ngis.dodlodging.net/propertys/Norfolk-NSY",
    name: "Norfolk Naval Shipyard ",
    proptype: "Navy Hotel",
  },
  {
    lat: 32.6892143,
    lon: -117.2083104,
    link: "https://get.dodlodging.net/propertys/Navy-Getaways-Coronado",
    name: "Coronado",
    proptype: "Navy VacationRental",
  },
  {
    lat: 41.567781,
    lon: -71.295041,
    link: "https://get.dodlodging.net/propertys/Carr-Point-RV-Park",
    name: "Carr Point RV Park",
    proptype: "Navy RV",
  },
  {
    lat: 36.789079,
    lon: -75.960975,
    link: "https://get.dodlodging.net/propertys/Cottages-at-Dam-Neck",
    name: "Cottages at Dam Neck",
    proptype: "Navy VacationRental",
  },
  {
    lat: 39.41489717,
    lon: -118.7250423,
    link: "https://get.dodlodging.net/propertys/Fallon-RV-Park",
    name: "Fallon RV Park",
    proptype: "Navy RV",
  },
  {
    lat: 35.339321,
    lon: -89.877614,
    link: "https://get.dodlodging.net/propertys/Mid-South-Cottages-and-RV-Parks",
    name: "Mid South Cottages and RV Parks",
    proptype: "Navy VacationRental",
  },
  {
    lat: 35.339321,
    lon: -89.877614,
    link: "https://get.dodlodging.net/propertys/Mid-South-Cottages-and-RV-Parks",
    name: "Mid South Cottages and RV Parks",
    proptype: "Navy RV",
  },
  {
    lat: 34.099016,
    lon: -119.104231,
    link: "https://get.dodlodging.net/propertys/Navy-Getaways-Point-Mugu-Beach-Hotel--RV-Park",
    name: "Navy Getaways Point Mugu Beach Hotel , RV Park",
    proptype: "Navy VacationRental",
  },
  {
    lat: 34.099016,
    lon: -119.104231,
    link: "https://get.dodlodging.net/propertys/Navy-Getaways-Point-Mugu-Beach-Hotel--RV-Park",
    name: "Navy Getaways Point Mugu Beach Hotel , RV Park",
    proptype: "Navy RV",
  },
  {
    lat: 32.72724,
    lon: -117.21597,
    link: "https://get.dodlodging.net/propertys/Point-Loma",
    name: "Navy Getaways Point Loma",
    proptype: "Navy VacationRental",
  },
  {
    lat: 32.72598,
    lon: -117.21624,
    link: "https://get.dodlodging.net/propertys/Point-Loma",
    name: "Navy Getaways Point Loma",
    proptype: "Navy RV",
  },
  {
    lat: 36.9094,
    lon: -76.16119,
    link: "https://get.dodlodging.net/propertys/JEB-Little-Creek-Campground-RV-Park",
    name: "JEB Little Creek Campground/RV Park",
    proptype: "Navy RV",
  },
  {
    lat: 30.391164,
    lon: -87.42224693,
    link: "https://get.dodlodging.net/propertys/Blue-Angel-Park",
    name: "Blue Angel Park",
    proptype: "Navy VacationRental",
  },
  {
    lat: 30.391164,
    lon: -87.42224693,
    link: "https://get.dodlodging.net/propertys/Blue-Angel-Park",
    name: "Blue Angel Park",
    proptype: "Navy RV",
  },
  {
    lat: 30.77214397,
    lon: -81.54979233,
    link: "https://get.dodlodging.net/propertys/Eagle-Hammock-RV-Park",
    name: "Eagle Hammock RV Park",
    proptype: "Navy VacationRental",
  },
  {
    lat: 30.77214397,
    lon: -81.54979233,
    link: "https://get.dodlodging.net/propertys/Eagle-Hammock-RV-Park",
    name: "Eagle Hammock RV Park",
    proptype: "Navy RV",
  },
  {
    lat: 40.26417,
    lon: -74.15742,
    link: "https://get.dodlodging.net/propertys/Navy-Getaways-Deer-Run-RV-Park",
    name: "Navy Getaways Deer Run RV Park",
    proptype: "Navy RV",
  },
  {
    lat: 30.2111419,
    lon: -81.6816888,
    link: "https://get.dodlodging.net/propertys/Heritage-Cottages",
    name: "Heritage Cottages",
    proptype: "Navy VacationRental",
  },
  {
    lat: 30.2197487,
    lon: -81.6821,
    link: "https://get.dodlodging.net/propertys/Jacksonville-RV-Park-and-Cottages",
    name: "Jacksonville RV Park and Cottages",
    proptype: "Navy RV",
  },
  {
    lat: 30.2197487,
    lon: -81.6821,
    link: "https://get.dodlodging.net/propertys/Jacksonville-RV-Park-and-Cottages",
    name: "Jacksonville RV Park and Cottages",
    proptype: "Navy VacationRental",
  },
  {
    lat: 30.342401,
    lon: -87.313907,
    link: "https://get.dodlodging.net/propertys/Oak-Grove-Park-Pensacola",
    name: "Oak Grove Park Pensacola",
    proptype: "Navy VacationRental",
  },
  {
    lat: 30.342401,
    lon: -87.313907,
    link: "https://get.dodlodging.net/propertys/Oak-Grove-Park-Pensacola",
    name: "Oak Grove Park Pensacola",
    proptype: "Navy RV",
  },
  {
    lat: 24.5621534,
    lon: -81.7953466,
    link: "https://get.dodlodging.net/propertys/Key-West-Vacations-Rentals",
    name: "Key West Vacations Rentals",
    proptype: "Navy VacationRental",
  },
  {
    lat: 32.406,
    lon: -86.248,
    link: "https://af.dodlodging.net/propertys/Gunter-AFB",
    name: "Gunter AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 29.824686,
    lon: -90.016803,
    link: "https://get.dodlodging.net/propertys/Aviation-Arbor-RV-Park",
    name: "Aviation Arbor RV Park",
    proptype: "Navy RV",
  },
  {
    lat: 35.7541746,
    lon: 139.3481827,
    link: "https://af.dodlodging.net/propertys/Yokota-AB",
    name: "Yokota AB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 39.71149,
    lon: -104.77188,
    link: "https://af.dodlodging.net/propertys/Buckley-AFB",
    name: "Buckley AFB",
    proptype: "Air Force Hotel",
  },
  {
    lat: 52.34462102,
    lon: 0.511250496,
    link: "https://af.dodlodging.net/propertys/RAF-Mildenhall",
    name: "RAF Mildenhall",
    proptype: "Air Force Hotel",
  },
  {
    lat: 29.39334,
    lon: -98.62722,
    link: "https://af.dodlodging.net/propertys/JBSA---Lackland",
    name: "JBSA   Lackland",
    proptype: "Air Force Hotel",
  },
  {
    lat: 48.723184,
    lon: 9.176015,
    link: "https://army.dodlodging.net/propertys/Stuttgart-Lodging---Kelley-Hotel",
    name: "Stuttgart Lodging   Kelley Hotel",
    proptype: "Army Hotel",
  },
  {
    lat: 48.684076,
    lon: 9.049859,
    link: "https://army.dodlodging.net/propertys/Stuttgart-Lodging---Panzer-Hotel",
    name: "Stuttgart Lodging   Panzer Hotel",
    proptype: "Army Hotel",
  },
  {
    lat: 44.40335,
    lon: -68.01298,
    link: "https://get.dodlodging.net/propertys/Gull-Cottage-Prospect-Harbor-Maine",
    name: "Gull Cottage Prospect Harbor Maine",
    proptype: "Navy VacationRental",
  },
  {
    lat: 38.2746878,
    lon: -76.4576172,
    link: "https://get.dodlodging.net/propertys/Goose-Creek-Campgrounds",
    name: "Goose Creek Campgrounds",
    proptype: "Navy RV",
  },
  {
    lat: 43.64428,
    lon: 10.35316,
    link: "https://army.dodlodging.net/propertys/Camp-Darby-Lodging",
    name: "Camp Darby Lodging",
    proptype: "Army Hotel",
  },
  {
    lat: 36.56956,
    lon: -76.24699,
    link: "https://get.dodlodging.net/propertys/Stewart-Campgrounds",
    name: "Stewart Campgrounds",
    proptype: "Navy RV",
  },
  {
    lat: 35.661309,
    lon: -117.644224,
    link: "https://get.dodlodging.net/propertys/China-Lake-RV-Park",
    name: "China Lake RV Park",
    proptype: "Navy RV",
  },
  {
    lat: 30.41206,
    lon: -86.49853,
    link: "https://army.dodlodging.net/propertys/Destin-Army-Recreation",
    name: "Destin Army Recreation",
    proptype: "Army VacationRental",
  },
  {
    lat: 30.411554,
    lon: -86.49781,
    link: "https://army.dodlodging.net/propertys/Destin-Army-Recreation",
    name: "Destin Army Recreation",
    proptype: "Army RV",
  },
  {
    lat: 35.33900413,
    lon: -89.87763762,
    link: "https://ngis.dodlodging.net/propertys/Mid-South-NSA",
    name: "NSA MID South",
    proptype: "Navy Hotel",
  },
  {
    lat: 38.876192,
    lon: -76.994988,
    link: "https://ngis.dodlodging.net/propertys/Navy-Yard-VFQ-NSA-Washington-DC",
    name: "Washington Navy Yard Visiting Flag Quarters",
    proptype: "Navy Hotel",
  },
  {
    lat: 30.707767,
    lon: -87.031986,
    link: "https://get.dodlodging.net/propertys/Clear-Creek-RV-Park",
    name: "Clear Creek RV Park",
    proptype: "Navy RV",
  },
  {
    lat: 36.789079,
    lon: -75.960975,
    link: "https://get.dodlodging.net/propertys/Sea-Mist-RV-Park",
    name: "Sea Mist RV Park",
    proptype: "Navy VacationRental",
  },
  {
    lat: 36.789079,
    lon: -75.960975,
    link: "https://get.dodlodging.net/propertys/Sea-Mist-RV-Park",
    name: "Sea Mist RV Park",
    proptype: "Navy RV",
  },
  {
    lat: 47.48442,
    lon: 11.05778,
    link: "https://army.dodlodging.net/propertys/Garmisch-Lodging",
    name: "Garmisch Lodging",
    proptype: "Army Hotel",
  },
  {
    lat: 32.65492895,
    lon: -114.5846571,
    link: "https://yuma.usmc-mccs.org/lodging/inns-of-the-corps",
    name: "Inns of the Corps Yuma",
    proptype: "inns of the corps",
  },
  {
    lat: 33.22700326,
    lon: -117.3885228,
    link: "https://pendleton.usmc-mccs.org/lodging/inns-of-the-corps/pacific-views",
    name: "Inns of the Corps Pendleton Pacific Views",
    proptype: "inns of the corps",
  },
  {
    lat: 33.30079989,
    lon: -117.3149608,
    link: "https://pendleton.usmc-mccs.org/lodging/inns-of-the-corps/ward-lodge",
    name: "Inns of the Corps Pendleton Ward Lodge",
    proptype: "inns of the corps",
  },
  {
    lat: 34.21231644,
    lon: -116.0440354,
    link: "https://29palms.usmc-mccs.org/lodging/inns-of-the-corps",
    name: "Inns of the Corps Twentynine Palms Desert View",
    proptype: "inns of the corps",
  },
  {
    lat: 34.21613954,
    lon: -116.0455962,
    link: "https://29palms.usmc-mccs.org/lodging/inns-of-the-corps",
    name: "Inns of the Corps Twentynine Palms Mountain View",
    proptype: "inns of the corps",
  },
  {
    lat: 32.88851135,
    lon: -117.120679,
    link: "http://www.mccsmiramar.com/miramar-inn/",
    name: "Inns of the Corps Miramar",
    proptype: "inns of the corps",
  },
  {
    lat: 21.43893751,
    lon: -157.7549855,
    link: "https://hawaii.usmc-mccs.org/lodging/inns-of-the-corps?",
    name: "Inns of the Corps Hawaii",
    proptype: "inns of the corps",
  },
  {
    lat: 26.38682083,
    lon: 127.8616635,
    link: "https://www.okinawa.usmc-mccs.org/about/camp-courtney/inns-of-the-corps-camp-courtneyIOTC?",
    name: "Inns of the Corps Camp Courtney",
    proptype: "inns of the corps",
  },
  {
    lat: 26.29784349,
    lon: 127.7843286,
    link: "https://www.okinawa.usmc-mccs.org/about/camp-foster/inns-of-the-corps-camp-fosterIOTC?",
    name: "Inns of the Corps Camp Foster",
    proptype: "inns of the corps",
  },
  {
    lat: 26.468821,
    lon: 127.9166555,
    link: "https://www.okinawa.usmc-mccs.org/about/camp-hansen/inns-of-the-corps-camp-hansen?",
    name: "Inns of the Corps Camp Hansen",
    proptype: "inns of the corps",
  },
  {
    lat: 34.15213012,
    lon: 132.2291524,
    link: "https://iwakuni.usmc-mccs.org/lodging/inns-of-the-corps",
    name: "Inns of the Corps Iwakuni",
    proptype: "inns of the corps",
  },
  {
    lat: 34.67131687,
    lon: -77.34031386,
    link: "https://lejeunenewriver.usmc-mccs.org/lodging/inns-of-the-corps",
    name: "Inns of the Corps Lejeune",
    proptype: "inns of the corps",
  },
  {
    lat: 32.45720797,
    lon: -80.72381346,
    link: "https://southcarolina.usmc-mccs.org/lodging/inns-of-the-corps-beaufort",
    name: "Inns of the Corps Beaufort",
    proptype: "inns of the corps",
  },
  {
    lat: 38.51053182,
    lon: -77.31240612,
    link: "https://quantico.usmc-mccs.org/lodging/inns-of-the-corps",
    name: "Inns of the Corps Quantico",
    proptype: "inns of the corps",
  },
  {
    lat: 32.98643585996508,
    lon: -114.47645751834736,
    link: "https://yuma.usmc-mccs.org/recreation-fitness/recreation/outdoor-recreation/campgrounds-rv",
    name: "MCAS Yuma, Venture Lodging at Lake Martinez",
    proptype: "marine getaways",
  },
  {
    lat: 34.236397,
    lon: -116.8861303,
    link: "http://www.mccsmiramar.com/big-bear-cabins/",
    name: "MCAS Miramar, Big Bear Recreational Facility",
    proptype: "marine getaways",
  },
  {
    lat: 33.22147380573457,
    lon: -117.40550160484678,
    link: "https://pendleton.usmc-mccs.org/lodging/beach-cottages/del-mar-beach-marina",
    name: "MCB Camp Pendleton, Del Mar Beach Resort & Marina",
    proptype: "marine getaways",
  },
  {
    lat: 33.33187973556962,
    lon: -117.32550243406084,
    link: "https://pendleton.usmc-mccs.org/lodging/campgrounds-rvs/lake-oneill",
    name: "MCB Camp Pendleton, Lake O Neill Recreation Park",
    proptype: "marine getaways",
  },
  {
    lat: 33.37997707276976,
    lon: -117.57196243850241,
    link: "https://pendleton.usmc-mccs.org/lodging/beach-cottages/san-onofre-beach?",
    name: "MCB Camp Pendleton, San Onofre Beach Resort",
    proptype: "marine getaways",
  },
  {
    lat: 34.874515409093256,
    lon: -116.95876867042448,
    link: "https://barstow.usmc-mccs.org/lodging/oasis-rv-park-lodging?",
    name: "MCLB Barstow, Oasis RV Park and Lodging",
    proptype: "marine getaways",
  },
  {
    lat: 31.554350378709607,
    lon: -84.03356527516743,
    link: "https://albany.usmc-mccs.org/lodging/rv-park?",
    name: "MCLB Albany RV Park",
    proptype: "marine getaways",
  },
  {
    lat: 21.452685236598303,
    lon: -157.77704784091085,
    link: "https://hawaii.usmc-mccs.org/lodging",
    name: "MCB Hawaii Aloha Cottages & Cabanas",
    proptype: "marine getaways",
  },
  {
    lat: 35.32079678383112,
    lon: 138.87603126822378,
    link: "https://campfuji.usmc-mccs.org/lodging?",
    name: "Camp Fuji, Mountain View Inn",
    proptype: "marine getaways",
  },
  {
    lat: 34.94168626398224,
    lon: -76.90237227226959,
    link: "https://cherrypoint.usmc-mccs.org/lodging/pelican-point-rv-park?",
    name: "MCAS Cherry Point, Pelican Point RV Park",
    proptype: "marine getaways",
  },
  {
    lat: 34.576416900604066,
    lon: -77.27012013986256,
    link: "https://lejeunenewriver.usmc-mccs.org/recreation-fitness/recreation/onslow-beach?",
    name: "MCB Camp Lejeune, Onslow Beach Resort",
    proptype: "marine getaways",
  },
  {
    lat: 32.47580535867183,
    lon: -80.7146659895257,
    link: "https://southcarolina.usmc-mccs.org/lodging/irbys-inn?",
    name: "MCAS Beaufort, Irby s Inn",
    proptype: "marine getaways",
  },
  {
    lat: 32.32853167269937,
    lon: -80.69494006521704,
    link: "https://southcarolina.usmc-mccs.org/lodging/parris-island-r-v-park?",
    name: "MCRD Parris Island, Parris Island RV Park",
    proptype: "marine getaways",
  },
  {
    lat: 32.65363955,
    lon: -114.5867047,
    link: "https://yuma.usmc-mccs.org/lodging/yuma-lodging",
    name: "Marine Lodge Yuma",
    proptype: "marine lodge",
  },
  {
    lat: 38.36084101,
    lon: -119.5144061,
    link: "https://bridgeport.usmc-mccs.org/lodging/transient-quarters-pathfinder-inn",
    name: "Marine Lodge Bridgeport Pathfinder Inn",
    proptype: "marine lodge",
  },
  {
    lat: 32.880296,
    lon: -117.135401,
    link: "https://www.miramar.marines.mil/Arriving/Billeting-Office/",
    name: "Marine Lodge Miramar",
    proptype: "marine lodge",
  },
  {
    lat: 32.7439822,
    lon: -117.1981524,
    link: "https://sandiego.usmc-mccs.org/lodging/lodging-at-mcrd-san-diego",
    name: "Marine Lodge San Diego",
    proptype: "marine lodge",
  },
  {
    lat: 34.236991452801824,
    lon: -116.05495031750014,
    link: "https://lodgingreservations.usmc-mccs.org/obookings3/Search/Index/15440/90/",
    name: "Marine Lodge Twentynine Palms Roadrunner",
    proptype: "marine lodge",
  },
  {
    lat: 31.545114446861945,
    lon: -84.03161451838533,
    link: "https://albany.usmc-mccs.org/lodging/live-oak-lodge",
    name: "Marine Lodge Albany Live Oak Lodge",
    proptype: "marine lodge",
  },
  {
    lat: 21.45219227667564,
    lon: -157.75548174558756,
    link: "https://hawaii.usmc-mccs.org/lodging/five-palms",
    name: "Marine Lodge Hawaii Five Palms",
    proptype: "marine lodge",
  },
  {
    lat: 26.297756924584956,
    lon: 127.78431791032718,
    link: "https://www.okinawa.usmc-mccs.org/about/mcas-futenma/cul-de-sac-inn",
    name: "Marine Lodge Futenma Cul de Sac Inn",
    proptype: "marine lodge",
  },
  {
    lat: 34.148879264192,
    lon: 132.22366148168462,
    link: "https://iwakuni.usmc-mccs.org/lodging/kintai-inn",
    name: "Marine Lodge Iwakuni Kintai Inn",
    proptype: "marine lodge",
  },
  {
    lat: 34.94052977,
    lon: -76.879759,
    link: "https://cherrypoint.usmc-mccs.org/lodging/cherry-point-inn",
    name: "Marine Lodge Cherry Point",
    proptype: "marine lodge",
  },
  {
    lat: 34.71201996,
    lon: -77.39574815,
    link: "https://www.allpointsinn.com/",
    name: "Marine Lodge Lejeune All Points Inn",
    proptype: "marine lodge",
  },
  {
    lat: 34.72285802700299,
    lon: -77.43178746360883,
    link: "https://lodgingreservations.usmc-mccs.org/obookings3/Search/Index/15438/90/",
    name: "Marine Lodge New River",
    proptype: "marine lodge",
  },
  {
    lat: 32.35190158668826,
    lon: -80.67373561651732,
    link: "https://southcarolina.usmc-mccs.org/lodging/osprey-inn",
    name: "Marine Lodge Parris Island Osprey Inn",
    proptype: "marine lodge",
  },
  {
    lat: 38.51054021073174,
    lon: -77.31240611633858,
    link: "https://quantico.usmc-mccs.org/lodging/liversedge-hall",
    name: "Marine Lodge Quantico Liversedge Hall",
    proptype: "marine lodge",
  },
  {
    lat: 46.12262059120913,
    lon: -123.93396938336646,
    link: "https://www.oregon.gov/omd/bservice/Pages/Reserve-Lodging-and-RV-Spaces.aspx",
    name: "Camp Rilea",
    proptype: "Army Vacation Rental",
  },
  {
    lat: 46.12024783608596,
    lon: -123.93651908489618,
    link: "https://www.oregon.gov/omd/bservice/Pages/Reserve-Lodging-and-RV-Spaces.aspx",
    name: " Camp Rilea ",
    proptype: "Army RV",
  },
];

export default properties;
